[package]
name = "tffile"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
log = "0.4.8"
failure = "0.1.8"
prost = "0.6.1"
bytes = "0.5.4"
crc = "1.8.1"
serde = { version = "1.0.110", features = ["derive"], optional = true }
futures = { version = "0.3.5", optional = true }
async-std = { version = "1.6.0", features = ["attributes"], optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
reqwest = { version = "0.10.4", features = ["blocking"] }

[build-dependencies]
glob = "0.3.0"
prost-build = "0.6.1"
failure = "0.1.8"
lazy_static = "1.4.0"

[features]
full = ["async_", "serde"]
async_ = ["futures", "async-std"]
