[package]
name = "tffile"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
log = "0.4.8"
failure = "0.1.8"
prost = "0.6.1"
bytes = "0.5.4"
crc = "1.8.1"
byteorder = "1.3.4"
serde = { version = "1.0.110", features = ["derive"] }

[dev-dependencies]

[build-dependencies]
glob = "0.3.0"
prost-build = "0.6.1"
failure = "0.1.8"
lazy_static = "1.4.0"
