[package]
name = "tfrecord"
description = "Serialize and deserialize TFRecord data format from TensorFlow"
version = "0.2.1"
authors = ["Jerry Lin <jerry73204@gmail.com>"]
edition = "2018"
categories = ["parsing"]
documentation = "https://docs.rs/tfrecord/"
repository = "https://github.com/jerry73204/rust-tfrecord.git"
homepage = "https://github.com/jerry73204/rust-tfrecord"
build = "build.rs"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
failure = "0.1"
prost = "0.6"
crc = "1.8"
serde = { version = "1.0", features = ["derive"], optional = true }
futures = { version = "0.3", optional = true }
async-std = { version = "1.6.1", features = ["attributes", "unstable"], optional = true }
num_cpus = { version = "1.13", optional = true }
tokio = { version = "0.2", features = ["sync"], optional = true }
static_assertions = { version = "1.1", optional = true }
noisy_float = "0.1"
atomig = "0.1"
image = { version = "0.23", optional = true }
tch = { version = "0.1", optional = true }
ndarray = { version = "0.13", optional = true }
hostname = "0.3"
integer-encoding = "1.1"

[dev-dependencies]
lazy_static = "1.4"
reqwest = { version = "0.10", features = ["blocking"] }
serde_json = "1.0"
rand = { version = "0.7", features = ["getrandom"] }
rand_distr = "0.2"
approx = "0.3"
flate2 = "1.0"
packed_struct = "0.3"
packed_struct_codegen = "0.3"
itertools = "0.9"

[build-dependencies]
glob = "0.3"
prost-build = "0.6"
failure = "0.1"
lazy_static = "1.4"
reqwest = { version = "0.10", features = ["blocking"] }
tar = "0.4"
flate2 = "1.0"
blake3 = "0.3"
hex = "0.4"

[features]
full = ["async_", "dataset", "summary", "with-tch", "with-image", "with-ndarray", "with-serde"]
async_ = ["futures", "async-std"]
generate_protobuf_src = []
dataset = ["async_", "num_cpus", "tokio", "static_assertions"]
summary = []
doc-only = ["tch/doc-only"]
with-tch = ["tch", "with-image"]
with-image = ["image"]
with-ndarray = ["ndarray"]
with-serde = ["serde"]

[package.metadata.docs.rs]
features = ["full", "doc-only"]
no-default-features = true
