[package]
name = "tfrecord"
description = "Serialize and deserialize TFRecord data format from TensorFlow"
version = "0.1.2"
authors = ["Jerry Lin <jerry73204@gmail.com>"]
edition = "2018"
categories = ["parsing"]
documentation = "https://docs.rs/tfrecord/"
repository = "https://github.com/jerry73204/rust-tfrecord.git"
homepage = "https://github.com/jerry73204/rust-tfrecord"
build = "build.rs"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
failure = "0.1.8"
prost = "0.6.1"
crc = "1.8.1"
serde = { version = "1.0", features = ["derive"], optional = true }
futures = { version = "0.3", optional = true }
async-std = { version = "1.6", features = ["attributes", "unstable"], optional = true }
num_cpus = { version = "1.13", optional = true }
tokio = { version = "0.2", features = ["sync"], optional = true }
static_assertions = { version = "1.1", optional = true }
noisy_float = "0.1"
atomig = "0.1"
image = { version = "0.23", optional = true }
tch = { version = "0.1", optional = true }
ndarray = { version = "0.13", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
reqwest = { version = "0.10.4", features = ["blocking"] }
serde_json = "1.0.53"
rand = { version = "0.7.3", features = ["getrandom"] }

[build-dependencies]
glob = "0.3.0"
prost-build = "0.6.1"
failure = "0.1.8"
lazy_static = "1.4.0"
reqwest = { version = "0.10.4", features = ["blocking"] }
tar = "0.4.28"
flate2 = "1.0.14"
blake3 = "0.3.4"
hex = "0.4.2"

[features]
full = ["async_", "serde", "dataset", "tch", "image", "ndarray"]
async_ = ["futures", "async-std"]
generate_protobuf_src = []
dataset = ["async_", "num_cpus", "tokio", "static_assertions"]

[package.metadata.docs.rs]
features = ["full"]
no-default-features = true
